[package]
name = "aoc-scraper"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
keywords.workspace = true

[dependencies]
futures = { workspace = true }
tokio = { workspace = true }
reqwest = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
tap = { workspace = true }
util = { path = "../util" }
scraper = "0.25"
